[2024-05-09T02:14:12.746+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T02:14:12.781+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_v1.choose_best_model manual__2024-05-09T02:07:43.320809+00:00 [queued]>
[2024-05-09T02:14:12.797+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_v1.choose_best_model manual__2024-05-09T02:07:43.320809+00:00 [queued]>
[2024-05-09T02:14:12.798+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-09T02:14:12.845+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-09 02:07:43.320809+00:00
[2024-05-09T02:14:12.859+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3480) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-09T02:14:12.863+0000] {standard_task_runner.py:63} INFO - Started process 3482 to run task
[2024-05-09T02:14:12.866+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag_v1', 'choose_best_model', 'manual__2024-05-09T02:07:43.320809+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp9sdudw7z']
[2024-05-09T02:14:12.871+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask choose_best_model
[2024-05-09T02:14:12.956+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag_v1.choose_best_model manual__2024-05-09T02:07:43.320809+00:00 [running]> on host 2b3626ba2b72
[2024-05-09T02:14:13.172+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='satyendra' AIRFLOW_CTX_DAG_ID='my_dag_v1' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T02:07:43.320809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T02:07:43.320809+00:00'
[2024-05-09T02:14:13.176+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T02:14:13.177+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-09T02:14:13.205+0000] {python.py:237} INFO - Done. Returned value was: inaccurate
[2024-05-09T02:14:13.206+0000] {branch.py:36} INFO - Branch into inaccurate
[2024-05-09T02:14:13.207+0000] {skipmixin.py:178} INFO - Following branch inaccurate
[2024-05-09T02:14:13.239+0000] {skipmixin.py:246} INFO - Skipping tasks [('accurate', -1)]
[2024-05-09T02:14:13.298+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T02:14:13.346+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=my_dag_v1, task_id=choose_best_model, execution_date=20240509T020743, start_date=20240509T021412, end_date=20240509T021413
[2024-05-09T02:14:13.405+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T02:14:13.457+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-09T02:14:13.464+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
