[2024-05-09T02:06:19.811+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T02:06:19.848+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_v1.choose_best_model manual__2024-05-09T02:06:11.499284+00:00 [queued]>
[2024-05-09T02:06:19.863+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_v1.choose_best_model manual__2024-05-09T02:06:11.499284+00:00 [queued]>
[2024-05-09T02:06:19.864+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-09T02:06:19.893+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-09 02:06:11.499284+00:00
[2024-05-09T02:06:19.905+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3387) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-09T02:06:19.907+0000] {standard_task_runner.py:63} INFO - Started process 3389 to run task
[2024-05-09T02:06:19.905+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag_v1', 'choose_best_model', 'manual__2024-05-09T02:06:11.499284+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmppuj_9vh9']
[2024-05-09T02:06:19.910+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask choose_best_model
[2024-05-09T02:06:19.991+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag_v1.choose_best_model manual__2024-05-09T02:06:11.499284+00:00 [running]> on host 2b3626ba2b72
[2024-05-09T02:06:20.139+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='satyendra' AIRFLOW_CTX_DAG_ID='my_dag_v1' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T02:06:11.499284+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T02:06:11.499284+00:00'
[2024-05-09T02:06:20.142+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T02:06:20.143+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-09T02:06:20.159+0000] {python.py:237} INFO - Done. Returned value was: inaccurate
[2024-05-09T02:06:20.160+0000] {branch.py:36} INFO - Branch into inaccurate
[2024-05-09T02:06:20.160+0000] {skipmixin.py:178} INFO - Following branch inaccurate
[2024-05-09T02:06:20.190+0000] {skipmixin.py:246} INFO - Skipping tasks [('accurate', -1)]
[2024-05-09T02:06:20.233+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T02:06:20.272+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=my_dag_v1, task_id=choose_best_model, execution_date=20240509T020611, start_date=20240509T020619, end_date=20240509T020620
[2024-05-09T02:06:20.324+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T02:06:20.366+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-09T02:06:20.370+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
